version: '3.1'
services:
  mongo:
    image: mongo:6.0
    container_name: mongo1
    restart: unless-stopped
    ports:
      - $MONGO_LOCAL_PORT:$MONGO_DOCKER_PORT
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USER
      - MONGO_INITDB_ROOT_PASSWORD==$MONGO_PASS
    volumes:
      - ./databases-data:/data/db
  mongo-express:
    image: mongo-express
    container_name: express1
    restart: unless-stopped
    links:
      - mongo
    ports:
      - $MONGO_EXPRESS_PORT:$MONGO_EXPRESS_PORT
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=$MONGO_USER
      - ME_CONFIG_MONGODB_ADMINPASSWORD=$MONGO_PASS
      - ME_CONFIG_MONGODB_URL=mongodb://$MONGO_USER:$MONGO_PASS@mongo:$MONGO_DOCKER_PORT/?authSource=admin
      - ME_CONFIG_BASICAUTH_USERNAME=$MONGO_EXPRESS_USER
      - ME_CONFIG_BASICAUTH_PASSWORD=$MONGO_EXPRESS_USER